[package]
name = "keyhole"
description = "keyhole is an rdb file parser written in Rust"
authors = ["Jacob Latonis <@jacoblatonis>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "rdb"
path = "src/rdb/lib.rs"

[dependencies]
nom = "7.1.3"
